<?php

return [
    'User Management' => [
        'True'                      => 'user_management_access',
        'ID'                        => 1
    ],
    'Permissions' => [
        'ID'                        => 1,
        'Create'                    => 'permission_create',
        'Edit'                      => 'permission_edit',
        'Show'                      => 'permission_show',
        'Delete'                    => 'permission_delete',
        'Access'                    => 'permission_access'
    ],
    'Roles' => [
        'ID'                        => 1,
        'Create'                    => 'role_create',
        'Edit'                      => 'role_edit',
        'Show'                      => 'role_show',
        'Delete'                    => 'role_delete',
        'Access'                    => 'role_access'
    ],
    'Users' => [
        'ID'                        => 1,
        'Create'                    => 'user_create',
        'Edit'                      => 'user_edit',
        'Show'                      => 'user_show',
        'Delete'                    => 'user_delete',
        'Access'                    => 'user_access',
        'Profile Password Edit'     => 'profile_password_edit',
    ],
    'Task Management' => [
        'ID'                        => 1,
        'Create'                    => 'task_create',
        'Edit'                      => 'task_edit',
        'All'                       => 'all_tasks_access',
        'Show'                      => 'task_show',
        'Delete'                    => 'task_delete',
        'Access'                    => 'task_access',
        'Action'                    => 'task_action'
    ],
    'Audit Logs' => [
        'ID'                        => 1,
        'Show'                      => 'audit_log_show',
        'Access'                    => 'audit_log_access',
        'View'                      => 'view_audit_log'
    ],
    'User Alert' => [
        'ID'                        => 1,
        'Create'                    => 'user_alert_create',
        'Show'                      => 'user_alert_show',
        'Delete'                    => 'user_alert_delete',
        'Access'                    => 'user_alert_access'
    ],
    'FAQ' => [
        'ID'                        => 1,
        'Create'                    => 'faq_category_create',
        'Edit'                      => 'faq_category_edit',
        'Show'                      => 'faq_category_show',
        'Delete'                    => 'faq_category_delete',
        'Access'                    => 'faq_category_access'
    ],
    'Operation Setup' => [
        'True'                      => 'master_data_access',
        'ID'                        => 2
    ],
    'Actions' => [
        'ID'                        => 2,
        'Create'                    => 'action_create',
        'Edit'                      => 'action_edit',
        'Show'                      => 'action_show',
        'Delete'                    => 'action_delete',
        'Access'                    => 'action_access'
    ],
    'Branch' => [
        'ID'                        => 2,
        'Create'                    => 'branch_create',
        'Edit'                      => 'branch_edit',
        'Show'                      => 'branch_show',
        'Delete'                    => 'branch_delete',
        'Access'                    => 'branch_access'
    ],
    'Status' => [
        'ID'                        => 2,
        'Create'                    => 'status_create',
        'Edit'                      => 'status_edit',
        'Show'                      => 'status_show',
        'Delete'                    => 'status_delete',
        'Access'                    => 'status_access'
    ],
    'Sources' => [
        'ID'                        => 2,
        'Create'                    => 'source_create',
        'Edit'                      => 'source_edit',
        'Show'                      => 'source_show',
        'Delete'                    => 'source_delete',
        'Access'                    => 'source_access'
    ],
    'Addresses' => [
        'ID'                        => 2,
        'Create'                    => 'address_create',
        'Edit'                      => 'address_edit',
        'Show'                      => 'address_show',
        'Delete'                    => 'address_delete',
        'Access'                    => 'address_access'
    ],
    'Expenses Category' => [
        'ID'                        => 2,
        'Create'                    => 'expenses_category_create',
        'Edit'                      => 'expenses_category_edit',
        'Show'                      => 'expenses_category_show',
        'Delete'                    => 'expenses_category_delete',
        'Access'                    => 'expenses_category_access'
    ],
    'Other Revenue Category' => [
        'ID'                        => 2,
        'Create'                    => 'external_payment_category_create',
        'Edit'                      => 'external_payment_category_edit',
        'Show'                      => 'external_payment_category_show',
        'Delete'                    => 'external_payment_category_delete',
        'Access'                    => 'external_payment_category_access'
    ],
    'Services Types' => [
        'ID'                        => 2,
        'Create'                    => 'service_type_create',
        'Edit'                      => 'service_type_edit',
        'Show'                      => 'service_type_show',
        'Delete'                    => 'service_type_delete',
        'Access'                    => 'service_type_access'
    ],
    'Service Options' => [
        'ID'                        => 2,
        'Create'                    => 'service_option_create',
        'Edit'                      => 'service_option_edit',
        'Show'                      => 'service_option_show',
        'Delete'                    => 'service_option_delete',
        'Access'                    => 'service_option_access',
    ],
    'Services' => [
        'ID'                        => 2,
        'Create'                    => 'service_create',
        'Edit'                      => 'service_edit',
        'Show'                      => 'service_show',
        'Delete'                    => 'service_delete',
        'Access'                    => 'service_access'
    ],
    'Pricelists' => [
        'ID'                        => 2,
        'Create'                    => 'pricelist_create',
        'Edit'                      => 'pricelist_edit',
        'Show'                      => 'pricelist_show',
        'Delete'                    => 'pricelist_delete',
        'Access'                    => 'pricelist_access'
    ],
    'Assets Types' => [
        'ID'                        => 2,
        'Create'                    => 'asset_type_create',
        'Edit'                      => 'asset_type_edit',
        'Show'                      => 'asset_type_show',
        'Delete'                    => 'asset_type_delete',
        'Access'                    => 'asset_type_access',
    ],
    'Assets' => [
        'ID'                        => 2,
        'Create'                    => 'asset_create',
        'Edit'                      => 'asset_edit',
        'Show'                      => 'asset_show',
        'Delete'                    => 'asset_delete',
        'Access'                    => 'asset_access',
    ],
    'Maintenance Vendors' => [
        'ID'                        => 2,
        'Create'                    => 'maintenance_vendor_create',
        'Edit'                      => 'maintenance_vendor_edit',
        'Show'                      => 'maintenance_vendor_show',
        'Delete'                    => 'maintenance_vendor_delete',
        'Access'                    => 'maintenance_vendor_access',
    ],
    'Member Statuses' => [
        'ID'                        => 2,
        'Create'                    => 'member_status_create',
        'Edit'                      => 'member_status_edit',
        'Show'                      => 'member_status_show',
        'Delete'                    => 'member_status_delete',
        'Access'                    => 'member_status_access',
    ],
    'Assets Maintenance' => [
        'ID'                        => 2,
        'Create'                    => 'assets_maintenance_create',
        'Edit'                      => 'assets_maintenance_edit',
        'Show'                      => 'assets_maintenance_show',
        'Delete'                    => 'assets_maintenance_delete',
        'Access'                    => 'assets_maintenance_access',
    ],
    'Refund Reasons' => [
        'ID'                        => 2,
        'Create'                    => 'refund_reason_create',
        'Edit'                      => 'refund_reason_edit',
        'Show'                      => 'refund_reason_show',
        'Delete'                    => 'refund_reason_delete',
        'Access'                    => 'refund_reason_access',
    ],
    'Timeslots' => [
        'ID'                        => 2,
        'Create'                    => 'timeslot_create',
        'Edit'                      => 'timeslot_edit',
        'Show'                      => 'timeslot_show',
        'Delete'                    => 'timeslot_delete',
        'Access'                    => 'timeslot_access',
    ],
    'Master Cards' => [
        'ID'                        => 2,
        'Create'                    => 'master_card_create',
        'Edit'                      => 'master_card_edit',
        'Show'                      => 'master_card_show',
        'Delete'                    => 'master_card_delete',
        'Access'                    => 'master_card_access',
    ],
    'Sessions Lists' => [
        'ID'                        => 2,
        'Create'                    => 'session_list_create',
        'Edit'                      => 'session_list_edit',
        'Show'                      => 'session_list_show',
        'Delete'                    => 'session_list_delete',
        'Access'                    => 'session_list_access',
    ],
    'Schedule Main' => [
        'ID'                        => 2,
        'Create'                    => 'schedule_main_create',
        'Edit'                      => 'schedule_main_edit',
        'Show'                      => 'schedule_main_show',
        'Delete'                    => 'schedule_main_delete',
        'Access'                    => 'schedule_main_access',
    ],
    'Schedules' => [
        'ID'                        => 2,
        'Create'                    => 'schedule_create',
        'Edit'                      => 'schedule_edit',
        'Show'                      => 'schedule_show',
        'Delete'                    => 'schedule_delete',
        'Access'                    => 'schedule_access',
    ],
    'Sales Tiers' => [
        'ID'                        => 2,
        'Create'                    => 'sales_tier_create',
        'Edit'                      => 'sales_tier_edit',
        'Show'                      => 'sales_tier_show',
        'Delete'                    => 'sales_tier_delete',
        'Access'                    => 'sales_tier_access',
    ],
    'Trainer Services' => [
        'ID'                        => 2,
        'Access'                    => 'trainer_services_access',
        'View'                      => 'trainer_services_view',
        'Create'                    => 'trainer_services_create',
        'Delete'                    => 'trainer_services_delete'
    ],
    'Sports' => [
        'ID'                        => 2,
        'Access'                    => 'sports_access',
        'View'                      => 'sports_view',
        'Create'                    => 'sports_create',
        'Delete'                    => 'sports_delete'
    ],
    'Operation Access' => [
        'True'                      => 'operations_access',
        'ID'                        => 3
    ],
    'Leads' => [
        'ID'                        => 3,
        'Create'                    => 'lead_create',
        'Edit'                      => 'lead_edit',
        'Show'                      => 'lead_show',
        'Delete'                    => 'lead_delete',
        'Access'                    => 'lead_access',
        'Transfer'                  => 'transfer_to_member',
        'Filter'                    => 'lead_filter',
        'Counter'                   => 'lead_counter',
        'Export'                    => 'export_leads',
        'Import'                    => 'lead_import',
    ],
    'Members' => [
        'ID'                        => 3,
        'Create'                    => 'member_create',
        'Edit'                      => 'member_edit',
        'Show'                      => 'member_show',
        'Delete'                    => 'member_delete',
        'Access'                    => 'member_access',
        'Add Membership'            => 'add_membership',
        'Take Action'               => 'take_action',
        'Filter'                    => 'member_filter',
        'Counter'                   => 'member_counter',
        'Edit Card Number'          => 'edit_card_number',
        'Edit Member Code'          => 'edit_member_code',
        'Export'                    => 'export_members',
        'Import'                    => 'member_import',
        'Add Notes'                 => 'add_notes',
        'Edit Notes'                => 'edit_notes',
        'Delete Notes'              => 'delete_notes',
        'Edit Sales By'             => 'edit_sales_by',
    ],
    'Memberships' => [
        'ID'                        => 3,
        'Create'                    => 'membership_create',
        'Edit'                      => 'membership_edit',
        'Show'                      => 'membership_show',
        'Delete'                    => 'membership_delete',
        'Access'                    => 'membership_access',
        'Filter'                    => 'membership_filter',
        'Counter'                   => 'membership_counter',
        'Upgrade'                   => 'upgrade_membership',
        'Downgrade'                 => 'downgrade_membership',
        'Transfer'                  => 'transfer_membership',
        'Renew'                     => 'renew_membership',
        'Export'                    => 'export_memberships',
    ],
    'Membership Attendances' => [
        'ID'                        => 3,
        'Create'                    => 'membership_attendance_create',
        'Edit'                      => 'membership_attendance_edit',
        'Show'                      => 'membership_attendance_show',
        'Delete'                    => 'membership_attendance_delete',
        'Access'                    => 'membership_attendance_access',
        'Expired Membership Attendances'      => 'view_expired_memberships_attendances',
        'Export'                    => 'export_membership_attendances',

    ],
    'Freeze Requests' => [
        'ID'                        => 3,
        'Create'                    => 'freeze_request_create',
        'Edit'                      => 'freeze_request_edit',
        'Show'                      => 'freeze_request_show',
        'Delete'                    => 'freeze_request_delete',
        'Access'                    => 'freeze_request_access',
        'Approve & Reject'          => 'approve_reject_freeze',
    ],
    'Coach Ratings' => [
        'ID'                        => 3,
        'Create'                    => 'ratings_create',
        'Edit'                      => 'ratings_edit',
        'Show'                      => 'ratings_show',
        'Delete'                    => 'ratings_delete',
        'Access'                    => 'ratings_access',
    ],
    'Member Requests Access' => [
        'ID'                        => 3,
        'Access'                    => 'member_requests_access',
        'View'                      => 'member_requests_view',
        'Create'                    => 'member_requests_create',
        'Delete'                    => 'member_requests_delete',
        'Decline & Approve'         => 'member_requests_approve',
        'Export'                    => 'export_member_requests',
    ],
    'Reminders' => [
        'ID'                        => 3,
        'Create'                    => 'reminder_create',
        'Edit'                      => 'reminder_edit',
        'Show'                      => 'reminder_show',
        'Delete'                    => 'reminder_delete',
        'Assign'                    => 'assign_reminder',
        'Access Reminders'          => 'reminder_access',
        'Today Reminders'           => 'view_today_reminders',
        'Upcoming Reminders'        => 'view_upcomming_reminders',
        'Overdue Reminders'         => 'view_overdue_reminders',
        'Reminders Management'      => 'view_reminders_management',
        'Reminders History'         => 'reminders_history'
    ],
    'Finance Access' => [
        'True'                      => 'finance_access',
        'ID'                        => 10
    ],
    'Expenses' => [
        'ID'                        => 10,
        'Create'                    => 'expense_create',
        'Edit'                      => 'expense_edit',
        'Show'                      => 'expense_show',
        'Delete'                    => 'expense_delete',
        'Access'                    => 'expense_access',
        'Filter'                    => 'expenses_filter',
        'Counter'                   => 'expenses_counter',
        'Export'                    => 'export_expenses',
    ],
    'Invoices' => [
        'ID'                        => 10,
        'Create'                    => 'invoice_create',
        'Edit'                      => 'invoice_edit',
        'Show'                      => 'invoice_show',
        'Delete'                    => 'invoice_delete',
        'Access'                    => 'invoice_access',
        'Filter'                    => 'invoice_filter',
        'Counter'                   => 'invoice_counter',
        'Change Date'               => 'invoice_change_date',
        'Editable End Date'         => 'editable_end_date',
        'Free Discount'             => 'free_discount',
        'Export'                    => 'export_invoices',
        'Partial Invoices'          => 'partial_invoice_access',
        'Export Partial Invoices'   => 'export_partial_invoices',
        'Settlement Invoice'        => 'settlement_invoice_access',
    ],
    'Payments' => [
        'ID'                        => 10,
        'Create'                    => 'payment_create',
        'Edit'                      => 'payment_edit',
        'Show'                      => 'payment_show',
        'Delete'                    => 'payment_delete',
        'Access'                    => 'payment_access',
        'Filter'                    => 'payment_filter',
        'Counter'                   => 'payment_counter',
        'Payment Date'              => 'edit_payment_date',
        'Export'                    => 'export_payments',
    ],
    'Refunds' => [
        'ID'                        => 10,
        'Create'                    => 'refund_create',
        'Edit'                      => 'refund_edit',
        'Show'                      => 'refund_show',
        'Delete'                    => 'refund_delete',
        'Access'                    => 'refund_access',
        'Filter'                    => 'refund_filter',
        'Counter'                   => 'refund_counter',
        'Approve & Reject'          => 'approve_reject_refund',
        'Export'                    => 'export_refunds',
    ],
    'Accounts' => [
        'ID'                        => 10,
        'Create'                    => 'account_create',
        'Edit'                      => 'account_edit',
        'Show'                      => 'account_show',
        'Delete'                    => 'account_delete',
        'Access'                    => 'account_access',
    ],
    'Other Revenues' => [
        'ID'                        => 10,
        'Create'                    => 'external_payment_create',
        'Edit'                      => 'external_payment_edit',
        'Show'                      => 'external_payment_show',
        'Delete'                    => 'external_payment_delete',
        'Access'                    => 'external_payment_access',
        'Filter'                    => 'external_payment_filter',
        'Counter'                   => 'external_payment_counter',
    ],
    'Loans' => [
        'ID'                        => 5,
        'Create'                    => 'loan_create',
        'Edit'                      => 'loan_edit',
        'Show'                      => 'loan_show',
        'Delete'                    => 'loan_delete',
        'Access'                    => 'loan_access',
        'Filter'                    => 'loan_filter',
        'Counter'                   => 'loan_counter',
    ],
    'Withdrwals' => [
        'ID'                        => 10,
        'Create'                    => 'withdrawal_create',
        'Edit'                      => 'withdrawal_edit',
        'Show'                      => 'withdrawal_show',
        'Delete'                    => 'withdrawal_delete',
        'Access'                    => 'withdrawal_access',
        'Filter'                    => 'withdrawal_filter',
        'Counter'                   => 'withdrawal_counter',
    ],
    'Transfer Sales Data'  => [
        'True'                      => 'view_transfer_sales_data',
        'ID'                        => 4
    ],
    'HR Management Access' => [
        'True'                      => 'hr_management_access',
        'ID'                        => 5
    ],
    'Schedule Template' => [
        'ID'                        => 5,
        'View'                      => 'view_schedule_template',
        'Delete'                    => 'delete_schedule_template',
        'Add'                       => 'add_schedule_template',
        'Edit'                      => 'edit_schedule_template'
    ],
    'Delay Rules' => [
        'ID'                        => 5,
        'View'                      => 'view_attendance_settings',
        'Create'                    => 'create_attendance_settings',
        'Edit'                      => 'edit_attendance_settings',
        'Delete'                    => 'delete_attendance_settings'
    ],
    'Employees' => [
        'ID'                        => 5,
        'Create'                    => 'employee_create',
        'Edit'                      => 'employee_edit',
        'Show'                      => 'employee_show',
        'Delete'                    => 'employee_delete',
        'Access'                    => 'employee_access',
        'Filter'                    => 'employee_filter',
        'Counter'                   => 'employee_counter',
    ],
    'Bonuses' => [
        'ID'                        => 5,
        'Create'                    => 'bonu_create',
        'Edit'                      => 'bonu_edit',
        'Show'                      => 'bonu_show',
        'Delete'                    => 'bonu_delete',
        'Access'                    => 'bonu_access',
        'Filter'                    => 'bonu_filter',
        'Counter'                   => 'bonu_counter',
    ],
    'Deductions' => [
        'ID'                        => 5,
        'Create'                    => 'deduction_create',
        'Edit'                      => 'deduction_edit',
        'Show'                      => 'deduction_show',
        'Delete'                    => 'deduction_delete',
        'Access'                    => 'deduction_access',
        'Filter'                    => 'deduction_filter',
        'Counter'                   => 'deduction_counter',
    ],
    'Loans' => [
        'ID'                        => 5,
        'Create'                    => 'loan_create',
        'Edit'                      => 'loan_edit',
        'Show'                      => 'loan_show',
        'Delete'                    => 'loan_delete',
        'Access'                    => 'loan_access',
        'Filter'                    => 'loan_filter',
        'Counter'                   => 'loan_counter',
    ],
    'Vacations' => [
        'ID'                        => 5,
        'Create'                    => 'vacation_create',
        'Edit'                      => 'vacation_edit',
        'Show'                      => 'vacation_show',
        'Delete'                    => 'vacation_delete',
        'Access'                    => 'vacation_access',
        'Counter'                   => 'vacation_counter',
    ],
    'Documents' => [
        'ID'                        => 5,
        'Create'                    => 'document_create',
        'Edit'                      => 'document_edit',
        'Show'                      => 'document_show',
        'Delete'                    => 'document_delete',
        'Access'                    => 'document_access',
    ],
    'Employee Attendances' => [
        'ID'                        => 5,
        'View'                      => 'view_employee_attendances',
        'Edit'                      => 'edit_employee_attendances',
        'Delete'                    => 'delete_employee_attendances',
        'Import'                    => 'import_employee_attendances',
        'Export'                    => 'export_employee_attendances',
    ],
    'Inventory Access' => [
        'True'                      => 'inventory_access',
        'ID'                        => 6
    ],
    'Warehouse' => [
        'ID'                        => 6,
        'Create'                    => 'warehouse_create',
        'Edit'                      => 'warehouse_edit',
        'Show'                      => 'warehouse_show',
        'Delete'                    => 'warehouse_delete',
        'Access'                    => 'warehouse_access',
    ],
    'Product' => [
        'ID'                        => 6,
        'Create'                    => 'product_create',
        'Edit'                      => 'product_edit',
        'Show'                      => 'product_show',
        'Delete'                    => 'product_delete',
        'Access'                    => 'product_access',
    ],
    'Warehouse Product' => [
        'ID'                        => 6,
        'Create'                    => 'warehouse_product_create',
        'Edit'                      => 'warehouse_product_edit',
        'Show'                      => 'warehouse_product_show',
        'Delete'                    => 'warehouse_product_delete',
        'Access'                    => 'warehouse_product_access',
    ],
    'Mobile App Access' => [
        'ID'                        => 8,
        'True'                      => 'mobile_app_access'
    ],
    'Hotdeals' => [
        'ID'                        => 8,
        'Create'                    => 'hotdeal_create',
        'Edit'                      => 'hotdeal_edit',
        'Show'                      => 'hotdeal_show',
        'Delete'                    => 'hotdeal_delete',
        'Access'                    => 'hotdeal_access',
    ],
    'Gallery Sections' => [
        'ID'                        => 8,
        'Create'                    => 'gallery_section_create',
        'Edit'                      => 'gallery_section_edit',
        'Show'                      => 'gallery_section_show',
        'Delete'                    => 'gallery_section_delete',
        'Access'                    => 'gallery_section_access',
    ],
    'Gallery' => [
        'ID'                        => 8,
        'Create'                    => 'gallery_create',
        'Edit'                      => 'gallery_edit',
        'Show'                      => 'gallery_show',
        'Delete'                    => 'gallery_delete',
        'Access'                    => 'gallery_access',
    ],
    'Video Sections' => [
        'ID'                        => 8,
        'Create'                    => 'video_section_create',
        'Edit'                      => 'video_section_edit',
        'Show'                      => 'video_section_show',
        'Delete'                    => 'video_section_delete',
        'Access'                    => 'video_section_access',
    ],
    'Videos' => [
        'ID'                        => 8,
        'Create'                    => 'video_create',
        'Edit'                      => 'video_edit',
        'Show'                      => 'video_show',
        'Delete'                    => 'video_delete',
        'Access'                    => 'video_access',
    ],
    'News Sections' => [
        'ID'                        => 8,
        'Create'                    => 'newssection_create',
        'Edit'                      => 'newssection_edit',
        'Show'                      => 'newssection_show',
        'Delete'                    => 'newssection_delete',
        'Access'                    => 'newssection_access',
    ],
    'News' => [
        'ID'                        => 8,
        'Create'                    => 'news_create',
        'Edit'                      => 'news_edit',
        'Show'                      => 'news_show',
        'Delete'                    => 'news_delete',
        'Access'                    => 'news_access',
    ],
//    'Mobile Settings' => [
//        'ID'                        => 8,
//        'Edit'                      => 'mobile_settings',
//
//    ],

    // 'Service Options Pricelists' => [
    //     'Create' => 'service_options_pricelist_create',
    //     'Edit' => 'service_options_pricelist_edit',
    //     'Show' => 'service_options_pricelist_show',
    //     'Delete' => 'service_options_pricelist_delete',
    //     'Access' => 'service_options_pricelist_access',
    // ],
    'Marketing Access' => [
        'ID'                        => 8,
        'Whatsapp'                  => 'whatsapp_access',
        'SMS'                       => 'sms_access',
        'Email Campaigns Access'    => 'email_campaigns_access',
        'Access'                    => 'markting_access'
    ],
    'Marketing Campaigns' => [
        'ID'                        => 8,
        'Create'                    => 'create_campaigns',
        'Edit'                      => 'edit_campaigns',
        'Delete'                    => 'delete_campaigns',
        'Access'                    => 'access_campaigns'
    ],
    'Reports Access' => [
        'ID'                        => 9,
        'True'                      => 'reports_access',
    ],

    'Members Reports' => [
        'ID'                        => 9,
        'Active Members'            => 'view_active_members',
        'Export Active Members'     => 'export_active_members',
        'Inactive Members'          => 'view_inactive_members',
        'Export Inactive Members'   => 'export_inactive_members',
        'Invitations Report'        => 'invitations_report',
        'Export Invitations Report' => 'export_invitations',
        'Invitations Delete'        => 'delete_invitations',
    ],

    'Memberships Reports' => [
        'ID'                        => 9,
        'Expired Memberships'       => 'expired_membership_access',
        'Export Expired Memberships' => 'export_expired_memberships',
        'Expiring Memberships'      => 'expiring_membership_access',
        'Export Expiring Memberships' => 'export_expiring_memberships',
        'Freezes'                   => 'view_freezes',
        'Export Freezes'            => 'export_freezes',
    ],

    'Markting Reports' => [
        'ID'                        => 9,
        'Leads Source Report'       => 'view_leads_source_report',
        'Member Sources Report'     => 'view_member_source_report',
        'Offers Report'             => 'view_offers_report',
    ],

    'Finance Analysis Reports' => [
        'ID'                        => 9,
        'Daily Report'              => 'view_daily_report',
        'Monthly Report'            => 'view_monthly_report',
        'Yearly Finance Report'     => 'view_yearly_finance_report',
        'Monthly Finance Report'    => 'view_monthly_finance_report',
        'Due Payments Report'       => 'due_payments_report',
        'Refund Reason Report'      => 'view_refund_reasons_report',
        'Expenses Report'           => 'view_expenses_report',
    ],

    'Reports' => [
        'ID'                        => 9,
        'Reminders Report'          => 'view_reminders_report',
        'Reminders Actions History Report' => 'view_reminders_actions_report',
        'Services Report'           => 'view_services_report',
        'Current Memberships Report' => 'view_current_memberships_report',
        'Sales Report'              => 'view_sales_report',
        'Sales Manager Report'      => 'view_sales_manager_report',
        'Freelancers Report'        => 'view_freelancers_report',
        'Revenue Report'            => 'view_revenue_report',
        'Export Revenue Report'     => 'export_revenues',
        'Coaches Report'            => 'view_coaches_report',
        'Export Coaches Report'     => 'export_coaches',
        'Trainers Report'           => 'view_trainers_report',
        'Export Trainers Report'    => 'export_trainers',
        'Payroll Page'              => 'view_payroll_page',
        // 'view_sitemap'              => 'Sitemap'
    ],
    'Other Access' => [
        'ID'                        => 9,
        // 'Schedule Access'           => 'schedule_access',
        'Schedule Timeline'         => 'view_schedule_timeline',
        'Settings Access'           => 'settings_access',
        'Take Attendance'           => 'take_attendance',
        'Data Migration'            => 'data_migration',
        'Help Center'               => 'help_center',
        'Update Invoice Date'       => 'update_invoice_date',
    ],
];
